setwd("E:/02-群体进化/07-结果/20250603-富集分析聚类/")
library(simplifyEnrichment)
library(org.Gg.eg.db)
library(org.Hs.eg.db)
library(ComplexHeatmap)
ego <- read.table("E:/02-群体进化/07-结果/202504-富集分析/GO-KEGG/BW/chicken/chicken_BW_pos_DCMS_top5_merged_regions_0kb_GO.txt",header = T)

library(rrvgo)
simMatrix <- calculateSimMatrix(ego$ID, orgdb="org.Gg.eg.db", ont="BP", method="Rel")
scores <- setNames(-log10(ego$qvalue), ego$ID)
reducedTerms <- reduceSimMatrix(simMatrix, scores, threshold=0.7, orgdb="org.Gg.eg.db")
scatterPlot(simMatrix, reducedTerms)
treemapPlot(reducedTerms)
wordcloudPlot(reducedTerms, min.freq=1, colors="black")
